# Root elements are available via `site.config`. Ex `site.config.mode`.
# production | development
mode: development


media_root: media
media_url: /media
base_url: /
# If your site is nested inside of a bigger one, you can use media_url and
# base_url to properly generate links on your site. For example, if your URL
# will be some.domain.com/starter/, use:
#   media_url: /starter/media
#   base_url: /starter/
template: hyde.ext.templates.jinja.Jinja2Template

plugins:
    # The plugin for reading meta.yaml and page top yaml content.
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin

# This defines data which is available in all pages.
# Don't define a data with name 'site'.
context:
    providers:
        # Updating providers data, require a server restart.
        contact: contact.yaml
    data:
        pages:
            - name: Overview
              url: /index.html
            - name: Generic
              url: /generic.html
            - name: Python
              url: /python.html
            - name: HTML/XML
              url: /html.html
            - name: JavaScript
              url: /javascript.html
            - name: CSS
              url: /css.html
            - name: Bash
              url: /bash.html
            - name: Review
              url: /review.html
            - name: Library
              url: /library.html
            - name: References
              url: /references.html
        site_info:
            name: Chevah StyleGuide
            favicon_png: img/favicon.png
            favicon_ico: img/favicon.ico
        author:
            name: Chevah Project
            url: http://www.chevah.com
            email: contact@chevah.com
            code_url: https://github.com/chevah/styleguide
            github_url: https://github.com/chevah


# This defines meta data on the whole site.
meta:
    # 'nodemeta' will tell Hyde what file to look for inside a folder from
    # which to apply meta data to all files (resources) inside it. This is
    # a great way of simply adding or modifying properties of a very large
    # number of files.
    nodemeta: meta.yaml
    default_block: content
    extends: one_column_menu_left.j2

restructuredtext:
    highlight_source: true
